server:
  port: 7001
  tomcat:
    uri-encoding: UTF-8
    # Tomcat默认大小2M, 超过2M的文件不会被捕获, 需要调整此处大小为100MB或者-1即可
    max-swallow-size: -1

spring:
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
