server:
  port: 7001
  tomcat:
    uri-encoding: UTF-8
    # Tomcat默认大小2M, 超过2M的文件不会被捕获, 需要调整此处大小为100MB或者-1即可
    max-swallow-size: -1

spring:
  application:
    name: hire-user
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.6:8849
        namespace: 6eaae543-e71b-4d98-afca-11c1eb2d8442
      config:
        server-addr: 192.168.1.6:8849
        file-extension: yaml
        namespace: 6eaae543-e71b-4d98-afca-11c1eb2d8442

mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
